name: NokomisLife
favicon: null
layout_spectrum: 0.46604792634025216
typography_spectrum: 0.09050034428946674
title: 'Connecting our great neighbors in South Minneapolis. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.834219572134316
  lightness: 0.6040759976021945
  saturation: 0.3112669256515801
  rhythmicContrast: 0.8962006208021194
purpose: []
